### ISSUE TITLE
The package does not seem to include Imagick

### ISSUE THREAD

**Issue by fengelbrekt** [Accudio/php-plaiceholder#3]
Hi,

I'm relatively new to php/laravel and so I may be doing something wrong. However, when trying to use php-plaiceholder I get errors due to Imagick not existing. It also seems like it can't be installed via composer (please correct me if I am wrong). Is the only way to use php-plaiceholder by manually installing imagick on each system intended to run the program?

**Comment by Accudio** [comment]
Hi, you are absolutely correct.

Imagick is a PHP extension that interfaces with ImageMagick, a system program. For setting up a server yourself you would install ImageMagick from the package repo and add the [Imagick PHP Extension](https://www.php.net/manual/en/book.imagick.php).

I believe that most web hosts either provide ImageMagick and Imagick by default, or will install it on request.

Are you trying to use it on a local server or with a web host?

**Comment by fengelbrekt** [comment]
Okay, that makes sense then! I have been trying to use it locally right now, with the intention to push the update to our VPS once it is working :) Do you know if it is possible to install the php extension via composer?

**Comment by Accudio** [comment]
Yeah, although a lot of local PHP setups don't include it—particularly on Windows—most hosting companies have it pre-installed.
Neither are possible to install with Composer as far as I know, the PHP extension requires changes to php.ini.

That said, although Imagick and ImageMagick are a lot easier to work with I should perhaps look at falling back to GD if Imagick isn't available.

Opened Issue #4 enhancement, regarding adding GD as a fallback.
